spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user
    username: fayupable
    password: fayupable
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true
        spring.json.type.mapping: userConfirmation:com.fayupable.mailsender.kafka.user.UserConfirmation

server:
  port: 8070

auth:
  token:
    expirationInMils: 3600000
    jwtSecret: YourSecretKey